### ISSUE TITLE
Develop Authentication (signUp/signIn) 

### ISSUE THREAD

**Issue by ramizapk** [202212-GIZ-YE-FEW/DevSquad#22]
**Task title**
Develop Authentication (signUp/signIn) 

**Task description**
Let user to signup or signIn.

**Subtasks**
 sign In:

- [x] Login with Email and Password.
- [x] Login with Google account.
- [x] Login with twitter account.

 sign up:

- [x] Create new user with user information.
- [x] Create new user with Google account.
- [x] Create new user with twitter account.
