### ISSUE TITLE
Develop Create Event Page

### ISSUE THREAD

**Issue by ramizapk** [202212-GIZ-YE-FEW/DevSquad#23]
**Task title**
Develop Create Event Page

**Task description**
Let user create an Event

**Subtasks**

- [x] let user add event location.
- [x] let user choose Event types.
- [x] let user add Event title and description.
- [x] let user upload Event image.
