### ISSUE TITLE
Develop User profile Page

### ISSUE THREAD

**Issue by ramizapk** [202212-GIZ-YE-FEW/DevSquad#24]
**Task title**
Develop User profile Page

**Task description**
let user add or edit personal information 

**Subtasks**

- [x] let user upload new image
- [x] let user write the name and location
- [x] let user choose its interests
- [x] let user change the password
