### ISSUE TITLE
Develop View Event Page

### ISSUE THREAD

**Issue by ramizapk** [202212-GIZ-YE-FEW/DevSquad#25]
**Task title**
Develop View Event Page

**Task description**
show event information and  attend people in the page.

**Subtasks**

- [x] show event information.
- [ ] show attend people.
- [ ] let user join event.

**Comment by rrawann** [comment]
I will add joinEvent function for let user join event  after authentication uploaded.
