### ISSUE TITLE
Translate home page

### ISSUE THREAD

**Issue by RuqaiahSaif** [202212-GIZ-YE-FEW/DevSquad#47]
**Task title**
Translate home page

**Task description**
Translate the home page and switch between Arabic and English

**Subtasks**

- [x] add language menu 
- [x] change rtl layout in the Arabic language
- [x] translate some sections on the home page

**Screenshots**
![lang1](https://user-images.githubusercontent.com/69811684/231836122-04f82bb4-c683-4ce2-8eb1-e8f7170de951.JPG)
![lang2](https://user-images.githubusercontent.com/69811684/231836153-9963c035-5a13-41c3-b29a-bd2584467fc8.JPG)

**Link to the component on Figma**
Put the link here
